server:
  servlet:
    context-path: /${REPO_NAME}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:auth-service}

  datasource:
    url: ${DATABASE_URL}
    username: ${AWS_RDS_SECRET_NAME:${DATABASE_USERNAME}}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show_sql: true

  cloud:
    kubernetes:
      discovery:
        enabled: ${KUBERNETES_ENABLED:true}
    openfeign:
      client:
        config:
          auth-service:
            url: ${AUTH_SERVICE_URL:#{null}}
          common-service:
            url: ${COMMON_SERVICE_URL:#{null}}

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.fancia.backend.shared.user.core.message
    bootstrap-servers: bootstrap.${DOMAIN_NAME}:9094

